@startuml
!include <C4/C4_Context>

Person(user, "User", "Пользователь")
Person(spec, "Specialist", "Специалист по подключению")
System(wh, "Warm House", "Система управления Теплый дом")
System_Ext(device, "Smart device", "Датчик или другое устройство умного дома")

Rel(user, wh, "Управляет", "Просматривает показания датчиков температуры, включает и выключает отопление")
Rel(spec, wh, "Настраивает", "Регистрирует устройства, настраивает систему")
Rel_U(wh, device, "Взаимодействует", "Опрашивает датчики температуры, посылает команды включения/выключения отопления")
@enduml